-- CreateEnum
CREATE TYPE "CommissionMode" AS ENUM ('PERCENTAGE', 'FLAT_PER_STUDENT');

-- AlterTable
ALTER TABLE "College" ADD COLUMN     "collegeFlatInr" INTEGER NOT NULL DEFAULT 120,
ADD COLUMN     "collegeFlatPremiumInr" INTEGER NOT NULL DEFAULT 160,
ADD COLUMN     "commissionMode" "CommissionMode" NOT NULL DEFAULT 'PERCENTAGE',
ADD COLUMN     "companyFlatInr" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "companyFlatPremiumInr" INTEGER NOT NULL DEFAULT 80,
ADD COLUMN     "courseFeeThreshold" INTEGER NOT NULL DEFAULT 5000,
ADD COLUMN     "mentorFlatInr" INTEGER NOT NULL DEFAULT 45,
ADD COLUMN     "mentorFlatPremiumInr" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "salesFlatInr" INTEGER NOT NULL DEFAULT 75,
ADD COLUMN     "salesFlatPremiumInr" INTEGER NOT NULL DEFAULT 100;
