import { MasterTrackDefinition } from './types';

/** 8 intensive weeks ≈ 6 months of engineering fundamentals (≈12–15 deep topics/week). */
export const MASTER_TRACKS: MasterTrackDefinition[] = [
  {
    slug: 'python-engineering-foundations',
    name: 'Python Engineering Foundations',
    tagline: 'Build backend systems, automation tools, and production-grade Python skills.',
    description:
      'An intensive 8-week program (equivalent to ~6 months of structured learning) covering Linux, Git, core Python, DSA, OOP, APIs, and a capstone sprint. Each week includes 12+ deep-dive topics with CLI labs, industry scenarios, and hands-on walkthroughs.',
    industryPositioning: [
      'building backend systems',
      'automation tools',
      'API integrations',
      'AI foundations',
      'problem solving',
      'debugging production-level issues',
    ],
    difficulty: 'BEGINNER',
    category: 'FOUNDATION',
    trackLevel: 1,
    estimatedWeeks: 8,
    isPlaceholder: false,
    weeks: [
      {
        week: 1,
        title: 'Engineering Setup & Computational Thinking',
        topics: [
          'Linux basics', 'terminal usage', 'file permissions & ownership', 'process management',
          'shell scripting intro', 'SSH & remote servers', 'environment variables & PATH',
          'VS Code mastery', 'Git & GitHub', 'Git branching & merging',
          'Python environment setup', 'pip & virtual environments',
          'debugging mindset', 'computational thinking',
        ],
        labs: ['terminal navigation', 'permissions & process lab', 'GitHub workflow exercises', 'SSH & remote lab', 'debugging exercises'],
        assignment: 'development environment automation checklist',
        miniProject: 'engineering workspace bootstrapper',
        interviewPrep: ['Git basics', 'developer tooling questions', 'Linux troubleshooting scenarios'],
      },
      {
        week: 2,
        title: 'Core Python Engineering',
        topics: [
          'variables', 'memory concepts', 'data types', 'type conversion & casting',
          'operators & expressions', 'string manipulation', 'string methods deep dive',
          'formatting & f-strings', 'input/output & stdin', 'Pythonic coding',
          'truthiness & boolean logic', 'constants & naming', 'error types & exceptions intro',
        ],
        labs: ['CLI utilities', 'validation systems', 'string processing lab', 'profile I/O lab'],
        assignment: 'student data processing system',
        miniProject: 'CLI profile manager',
        interviewPrep: ['output prediction', 'debugging questions', 'Python memory & references'],
      },
      {
        week: 3,
        title: 'Logic Building & Algorithmic Thinking',
        topics: [
          'conditions', 'loops', 'for vs while patterns', 'nested logic',
          'break continue pass', 'pattern printing', 'FizzBuzz & classic problems',
          'algorithm thinking', 'pseudocode & flowcharts', 'computational optimization',
          'debugging loops', 'iteration patterns',
        ],
        labs: ['pattern generators', 'logic simulators', 'classic problem set', 'ATM logic lab'],
        assignment: 'ATM transaction engine',
        miniProject: 'banking simulator',
        interviewPrep: ['logical coding rounds', 'complexity basics in loops'],
      },
      {
        week: 4,
        title: 'Functional Programming & Modular Systems',
        topics: [
          'functions', 'parameters & return values', 'scope & namespaces', 'recursion',
          'lambda functions', 'map/filter/reduce', 'decorators intro',
          'modular architecture', 'packages & imports', 'docstrings & type hints', 'testing functions',
        ],
        labs: ['reusable utility modules', 'recursion workshop', 'decorator patterns lab', 'package structure lab'],
        assignment: 'expense analytics engine',
        miniProject: 'modular utility toolkit',
        interviewPrep: ['recursion', 'reusable code architecture', 'function design questions'],
      },
      {
        week: 5,
        title: 'Data Structures & Problem Solving',
        topics: [
          'arrays & lists', 'stacks', 'queues', 'dictionaries deep dive',
          'sets & frozensets', 'tuples & immutability', 'searching algorithms',
          'sorting algorithms', 'time complexity', 'space complexity', 'Big-O analysis', 'problem-solving patterns',
        ],
        labs: ['coding challenge systems', 'stack & queue lab', 'sorting visualizer', 'LeetCode-style drills'],
        assignment: 'inventory optimization engine',
        miniProject: 'DSA challenge platform',
        interviewPrep: ['coding rounds', 'algorithm optimization', 'Big-O interview questions'],
      },
      {
        week: 6,
        title: 'OOP & Software Design',
        topics: [
          'OOP fundamentals', 'classes & objects', 'inheritance', 'polymorphism',
          'abstraction & ABCs', 'encapsulation', 'magic methods',
          'SOLID basics', 'composition vs inheritance', 'design patterns intro',
        ],
        labs: ['software architecture exercises', 'OOP modeling lab', 'SOLID refactor lab', 'ERP domain lab'],
        assignment: 'payroll system',
        miniProject: 'School ERP backend',
        interviewPrep: ['OOP design interviews', 'SOLID principles scenarios'],
      },
      {
        week: 7,
        title: 'APIs, Automation & Integrations',
        topics: [
          'REST APIs', 'HTTP methods & status codes', 'JSON & serialization', 'requests library',
          'API authentication basics', 'automation scripting', 'web scraping ethics & tools',
          'schedulers & cron', 'error handling in integrations', 'API testing with curl',
        ],
        labs: ['API integration workflows', 'curl & Postman lab', 'automation cron lab', 'scraper ethics lab'],
        assignment: 'API-integrated dashboard',
        miniProject: 'productivity automation platform',
        interviewPrep: ['API debugging', 'real-world integrations', 'HTTP & REST scenarios'],
      },
      {
        week: 8,
        title: 'Capstone Engineering Sprint',
        topics: [
          'capstone planning', 'requirements & user stories', 'architecture design', 'system diagrams',
          'testing strategy', 'deployment', 'CI/CD intro', 'documentation',
          'presentation skills', 'portfolio & resume', 'interview consolidation',
        ],
        labs: ['capstone implementation sprint', 'deploy to staging lab', 'demo rehearsal lab'],
        assignment: 'capstone milestone submission',
        miniProject: 'capstone project delivery',
        interviewPrep: ['aptitude', 'Python interviews', 'debugging interviews', 'HR simulations', 'GitHub portfolio review', 'resume preparation'],
        capstone: true,
      },
    ],
    capstoneOptions: ['productivity platform', 'automation suite', 'analytics dashboard', 'AI-powered utility platform'],
    capstoneRequirements: ['GitHub repository', 'documentation', 'deployment', 'architecture explanation', 'presentation'],
  },
  {
    slug: 'full-stack-product-engineering',
    name: 'Full Stack Product Engineering',
    tagline: 'Train like a junior software engineer — React, Next.js, NestJS, PostgreSQL, Docker.',
    description:
      'Intensive 8-week full-stack program (~6 months equivalent): modern frontend, backend APIs, databases, auth, real-time, DevOps, capstone. 12+ deep topics per week with CLI workflows (npm, Docker, psql, curl).',
    techStack: ['React', 'Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'Prisma', 'Docker', 'Redis', 'WebSockets'],
    difficulty: 'INTERMEDIATE',
    category: 'SPECIALIZATION',
    trackLevel: 2,
    estimatedWeeks: 8,
    isPlaceholder: true,
    weeks: [
      {
        week: 1,
        title: 'Modern Frontend Foundations',
        topics: [
          'React internals', 'JSX & rendering', 'component architecture', 'props & state',
          'hooks', 'useEffect & data fetching', 'TypeScript', 'type-safe components',
          'reusable systems', 'Tailwind & styling', 'accessibility basics', 'React DevTools',
        ],
        labs: ['component library labs', 'hook pattern exercises', 'TypeScript refactor lab', 'a11y audit lab'],
        assignment: 'reusable UI component library',
        miniProject: 'dashboard UI system',
        interviewPrep: ['React fundamentals', 'component design', 'React performance questions'],
      },
      {
        week: 2,
        title: 'Advanced Frontend Engineering',
        topics: [
          'Next.js App Router', 'file-based routing', 'SSR/CSR/SSG/ISR', 'Server vs Client Components',
          'data fetching patterns', 'auth flows', 'middleware & route guards',
          'frontend optimization', 'Core Web Vitals', 'SEO fundamentals', 'error & loading UI',
        ],
        labs: ['routing labs', 'SSR vs CSR comparison', 'auth middleware lab', 'Lighthouse optimization lab'],
        assignment: 'optimized landing page',
        miniProject: 'authentication platform',
        interviewPrep: ['Next.js interviews', 'rendering strategies', 'frontend system design'],
      },
      {
        week: 3,
        title: 'Backend API Engineering',
        topics: [
          'NestJS/Express', 'RESTful design', 'modular backend systems', 'controllers & services',
          'middleware', 'validation & DTOs', 'error handling & filters', 'scalable APIs',
          'API versioning', 'OpenAPI & Swagger', 'integration testing', 'logging & observability',
        ],
        labs: ['REST API labs', 'middleware exercises', 'DTO validation lab', 'Swagger documentation lab'],
        assignment: 'CRUD API with validation',
        miniProject: 'production API service',
        interviewPrep: ['backend API design', 'middleware patterns', 'REST vs GraphQL'],
      },
      {
        week: 4,
        title: 'Database Engineering',
        topics: [
          'PostgreSQL', 'SQL fundamentals', 'indexing', 'query plans & EXPLAIN',
          'Prisma ORM', 'schema design', 'schema optimization', 'migrations',
          'transactions & ACID', 'relationships & joins', 'seeding & fixtures', 'N+1 problem',
        ],
        labs: ['schema design labs', 'query optimization', 'Prisma migration lab', 'transaction lab'],
        assignment: 'database schema design',
        miniProject: 'multi-tenant backend',
        interviewPrep: ['SQL interviews', 'ORM patterns', 'database normalization'],
      },
      {
        week: 5,
        title: 'Authentication & Security',
        topics: [
          'JWT', 'session vs token auth', 'RBAC', 'OAuth & social login',
          'password hashing', 'rate limiting', 'CORS & CSRF', 'API security',
          'Helmet & security headers', 'secrets management', 'security testing',
        ],
        labs: ['auth flow labs', 'RBAC exercises', 'OAuth integration lab', 'security headers lab'],
        assignment: 'secure auth implementation',
        miniProject: 'enterprise auth platform',
        interviewPrep: ['security interviews', 'JWT deep dive', 'OWASP API top 10'],
      },
      {
        week: 6,
        title: 'Real-Time Engineering',
        topics: [
          'WebSockets', 'Socket.io patterns', 'Redis', 'pub/sub messaging',
          'queues & BullMQ', 'notifications architecture', 'async systems',
          'event-driven design', 'idempotency', 'backpressure & scaling',
        ],
        labs: ['WebSocket labs', 'queue exercises', 'Redis cache lab', 'notification fan-out lab'],
        assignment: 'real-time notification system',
        miniProject: 'collaboration platform',
        interviewPrep: ['real-time system design', 'WebSocket vs SSE', 'message queue scenarios'],
      },
      {
        week: 7,
        title: 'DevOps & Deployment',
        topics: [
          'Docker', 'Docker Compose', 'multi-stage builds', 'CI/CD',
          'GitHub Actions', 'nginx reverse proxy', 'SSL & Certbot',
          'monitoring & health checks', 'VPS deployment', 'environment configs', 'rollback strategies',
        ],
        labs: ['Docker compose labs', 'CI pipeline setup', 'nginx config lab', 'production deploy lab'],
        assignment: 'containerized deployment',
        miniProject: 'deployed SaaS application',
        interviewPrep: ['DevOps fundamentals', 'deployment scenarios', 'Docker interview questions'],
      },
      {
        week: 8,
        title: 'Full Stack Industry Capstone',
        topics: [
          'system architecture', 'monolith vs microservices', 'CI/CD integration',
          'production deployment', 'code review', 'technical documentation',
          'performance tuning', 'incident response', 'capstone demo prep',
        ],
        labs: ['capstone sprint', 'load testing lab', 'postmortem writing lab'],
        assignment: 'capstone milestone review',
        miniProject: 'full-stack capstone delivery',
        interviewPrep: ['frontend interviews', 'backend interviews', 'machine coding rounds', 'architecture discussions'],
        capstone: true,
      },
    ],
    capstoneOptions: ['LMS platform', 'AI workflow platform', 'HRMS system', 'project management SaaS'],
    capstoneRequirements: ['production deployment', 'Dockerized infrastructure', 'architecture review', 'CI/CD workflows'],
  },
  {
    slug: 'ai-engineering-intelligent-systems',
    name: 'AI Engineering & Intelligent Systems',
    tagline: 'Build RAG systems, AI agents, and production-grade intelligent applications.',
    description:
      'Intensive 8-week AI engineering track (~6 months equivalent): transformers, LLM APIs, RAG, agents, scalable backends, AI UX, deployment. Deep CLI labs with curl, uvicorn, vector DBs, and cost monitoring.',
    techStack: ['Python', 'FastAPI', 'LangChain', 'Vector Databases', 'Qwen/OpenAI APIs', 'RAG Systems'],
    difficulty: 'ADVANCED',
    category: 'SPECIALIZATION',
    trackLevel: 3,
    estimatedWeeks: 8,
    isPlaceholder: true,
    weeks: [
      {
        week: 1,
        title: 'AI Foundations',
        topics: [
          'transformers', 'attention mechanism', 'embeddings', 'vector similarity',
          'tokenization', 'BPE & SentencePiece', 'prompt engineering',
          'LLM architecture', 'context windows', 'hallucinations & limitations', 'model selection',
        ],
        labs: ['embedding labs', 'prompt experiments', 'token counting lab', 'similarity search lab'],
        assignment: 'prompt engineering portfolio',
        miniProject: 'prompt experimentation platform',
        interviewPrep: ['LLM fundamentals', 'transformer architecture', 'embedding interview questions'],
      },
      {
        week: 2,
        title: 'AI API Engineering',
        topics: [
          'OpenAI APIs', 'chat completions', 'Qwen integration', 'API keys & security',
          'streaming AI responses', 'SSE & chunked responses', 'token optimization',
          'retry & rate limits', 'structured outputs', 'function calling intro', 'cost tracking',
        ],
        labs: ['API integration labs', 'streaming exercises', 'retry middleware lab', 'cost dashboard lab'],
        assignment: 'streaming chat API',
        miniProject: 'AI assistant platform',
        interviewPrep: ['AI API design', 'token optimization', 'streaming architecture'],
      },
      {
        week: 3,
        title: 'RAG Engineering',
        topics: [
          'vector databases', 'pgvector & Pinecone', 'semantic search', 'hybrid search',
          'retrieval pipelines', 'chunking strategies', 'document ingestion',
          'reranking', 'evaluation metrics', 'RAG failure modes', 'citation & grounding',
        ],
        labs: ['vector DB labs', 'chunking exercises', 'ingestion pipeline lab', 'RAG eval lab'],
        assignment: 'document retrieval pipeline',
        miniProject: 'document intelligence platform',
        interviewPrep: ['RAG architecture', 'retrieval evaluation', 'chunking trade-offs'],
      },
      {
        week: 4,
        title: 'AI Agents & Workflows',
        topics: [
          'tool calling', 'ReAct pattern', 'memory systems', 'short & long-term memory',
          'autonomous workflows', 'human-in-the-loop', 'multi-agent orchestration',
          'agent safety', 'max iteration limits', 'observability for agents',
        ],
        labs: ['agent workflow labs', 'tool calling exercises', 'memory store lab', 'multi-agent lab'],
        assignment: 'multi-step agent workflow',
        miniProject: 'AI workflow agent',
        interviewPrep: ['agent design patterns', 'tool calling scenarios', 'agent safety questions'],
      },
      {
        week: 5,
        title: 'Scalable AI Backends',
        topics: [
          'FastAPI', 'async AI systems', 'background tasks', 'caching LLM responses',
          'queues for inference', 'scaling AI APIs', 'connection pooling',
          'timeout & circuit breakers', 'batch embedding', 'API gateway patterns',
        ],
        labs: ['async API labs', 'queue integration', 'Redis cache lab', 'load test lab'],
        assignment: 'cached AI endpoint',
        miniProject: 'scalable AI backend',
        interviewPrep: ['AI backend scaling', 'async Python patterns', 'caching strategies'],
      },
      {
        week: 6,
        title: 'AI Frontend Engineering',
        topics: [
          'streaming UI', 'SSE client patterns', 'AI chat UX', 'message components',
          'markdown rendering', 'syntax highlighting', 'AI copilots',
          'stop & regenerate', 'conversation history', 'accessibility in chat UI',
        ],
        labs: ['streaming UI labs', 'chat component exercises', 'markdown sanitizer lab', 'copilot panel lab'],
        assignment: 'streaming chat interface',
        miniProject: 'Claude-style AI interface',
        interviewPrep: ['AI UX patterns', 'streaming frontend design', 'chat state management'],
      },
      {
        week: 7,
        title: 'AI Deployment & Optimization',
        topics: [
          'inference optimization', 'quantization basics', 'prompt caching',
          'monitoring AI systems', 'Langfuse & tracing', 'AI cost optimization',
          'GPU deployment basics', 'vLLM & Ollama', 'SLAs for AI features', 'fallback strategies',
        ],
        labs: ['monitoring setup', 'cost analysis exercises', 'Ollama local lab', 'fallback UX lab'],
        assignment: 'AI cost optimization report',
        miniProject: 'optimized AI service',
        interviewPrep: ['AI ops', 'cost optimization', 'production LLM monitoring'],
      },
      {
        week: 8,
        title: 'AI Engineering Capstone',
        topics: [
          'AI system architecture', 'vector DB integration', 'production deployment',
          'monitoring & alerts', 'security for AI apps', 'capstone integration',
          'demo & storytelling', 'AI portfolio presentation',
        ],
        labs: ['capstone AI sprint', 'end-to-end RAG deploy lab', 'capstone demo lab'],
        assignment: 'capstone AI milestone',
        miniProject: 'AI capstone delivery',
        interviewPrep: ['AI engineering interviews', 'prompt engineering rounds', 'AI architecture discussions'],
        capstone: true,
      },
    ],
    capstoneOptions: ['AI interviewer', 'AI coding assistant', 'AI tutor', 'AI resume analyzer', 'AI automation workflow system'],
    capstoneRequirements: ['scalable architecture', 'vector database integration', 'production deployment', 'monitoring system'],
  },
];
