-- AlterTable
ALTER TABLE "College" ADD COLUMN     "collegeCommissionPct" DOUBLE PRECISION NOT NULL DEFAULT 30,
ADD COLUMN     "companyProfitPct" DOUBLE PRECISION NOT NULL DEFAULT 45,
ADD COLUMN     "mentorCommissionPct" DOUBLE PRECISION NOT NULL DEFAULT 10,
ADD COLUMN     "salesCommissionPct" DOUBLE PRECISION NOT NULL DEFAULT 15;
