/** Maps expanded curriculum topic titles → existing knowledge keys. */
export const TOPIC_ALIASES: Record<string, string> = {
  'file permissions & ownership': 'linux basics',
  'process management': 'linux basics',
  'shell scripting intro': 'terminal usage',
  'ssh & remote servers': 'linux basics',
  'environment variables & path': 'terminal usage',
  'git branching & merging': 'git & github',
  'pip & virtual environments': 'python environment setup',
  'type conversion & casting': 'data types',
  'operators & expressions': 'data types',
  'string methods deep dive': 'string manipulation',
  'formatting & f-strings': 'formatting',
  'input/output & stdin': 'variables',
  'truthiness & boolean logic': 'data types',
  'constants & naming': 'variables',
  'error types & exceptions intro': 'debugging mindset',
  'collections overview': 'data types',
  'for vs while patterns': 'loops',
  'break continue pass': 'loops',
  'pattern printing': 'loops',
  'fizzbuzz & classic problems': 'loops',
  'pseudocode & flowcharts': 'algorithm thinking',
  'debugging loops': 'loops',
  'iteration patterns': 'loops',
  'parameters & return values': 'functions',
  'scope & namespaces': 'functions',
  'lambda functions': 'lambda',
  'decorators intro': 'functions',
  'packages & imports': 'modular architecture',
  'docstrings & type hints': 'functions',
  'testing functions': 'functions',
  'arrays & lists': 'arrays',
  'dictionaries deep dive': 'dictionaries',
  'sets & frozensets': 'sets',
  'tuples & immutability': 'data types',
  'searching algorithms': 'searching/sorting',
  'sorting algorithms': 'searching/sorting',
  'space complexity': 'time complexity',
  'big-o analysis': 'time complexity',
  'problem-solving patterns': 'algorithm thinking',
  'oop fundamentals': 'oop',
  'classes & objects': 'oop',
  'abstraction & abcs': 'abstraction',
  'magic methods': 'oop',
  'composition vs inheritance': 'inheritance',
  'design patterns intro': 'solid basics',
  'http methods & status codes': 'rest apis',
  'json & serialization': 'json',
  'api authentication basics': 'rest apis',
  'web scraping ethics & tools': 'web scraping',
  'schedulers & cron': 'schedulers',
  'error handling in integrations': 'rest apis',
  'api testing with curl': 'rest apis',
  'requirements & user stories': 'capstone planning',
  'system diagrams': 'architecture design',
  'testing strategy': 'capstone planning',
  'ci/cd intro': 'deployment',
  'portfolio & resume': 'documentation',
  'interview consolidation': 'presentation skills',
  'jsx & rendering': 'react internals',
  'props & state': 'react internals',
  'useeffect & data fetching': 'hooks',
  'type-safe components': 'typescript',
  'tailwind & styling': 'reusable systems',
  'accessibility basics': 'component architecture',
  'react devtools': 'react internals',
  'file-based routing': 'next.js app router',
  'server vs client components': 'ssr/csr',
  'data fetching patterns': 'next.js app router',
  'middleware & route guards': 'auth flows',
  'core web vitals': 'frontend optimization',
  'seo fundamentals': 'frontend optimization',
  'error & loading ui': 'next.js app router',
  'restful design': 'nestjs/express',
  'controllers & services': 'nestjs/express',
  'validation & dtos': 'validation',
  'error handling & filters': 'middleware',
  'api versioning': 'scalable apis',
  'openapi & swagger': 'scalable apis',
  'integration testing': 'scalable apis',
  'logging & observability': 'monitoring',
  'sql fundamentals': 'postgresql',
  'query plans & explain': 'indexing',
  'migrations': 'prisma orm',
  'relationships & joins': 'postgresql',
  'seeding & fixtures': 'prisma orm',
  'n+1 problem': 'prisma orm',
  'session vs token auth': 'jwt',
  'password hashing': 'jwt',
  'cors & csrf': 'api security',
  'helmet & security headers': 'api security',
  'secrets management': 'api security',
  'security testing': 'api security',
  'socket.io patterns': 'websockets',
  'pub/sub messaging': 'redis',
  'queues & bullmq': 'queues',
  'notifications architecture': 'notifications',
  'event-driven design': 'async systems',
  'idempotency': 'queues',
  'backpressure & scaling': 'async systems',
  'docker compose': 'docker',
  'multi-stage builds': 'docker',
  'github actions': 'ci/cd',
  'ssl & certbot': 'nginx',
  'environment configs': 'vps deployment',
  'rollback strategies': 'production deployment',
  'monolith vs microservices': 'system architecture',
  'technical documentation': 'documentation',
  'performance tuning': 'frontend optimization',
  'incident response': 'monitoring',
  'capstone demo prep': 'presentation skills',
  'attention mechanism': 'transformers',
  'vector similarity': 'embeddings',
  'bpe & sentencepiece': 'tokenization',
  'context windows': 'llm architecture',
  'hallucinations & limitations': 'llm architecture',
  'model selection': 'llm architecture',
  'chat completions': 'openai apis',
  'api keys & security': 'openai apis',
  'sse & chunked responses': 'streaming ai responses',
  'retry & rate limits': 'openai apis',
  'structured outputs': 'prompt engineering',
  'function calling intro': 'tool calling',
  'cost tracking': 'token optimization',
  'pgvector & pinecone': 'vector databases',
  'hybrid search': 'semantic search',
  'document ingestion': 'retrieval pipelines',
  'reranking': 'semantic search',
  'evaluation metrics': 'semantic search',
  'rag failure modes': 'retrieval pipelines',
  'citation & grounding': 'retrieval pipelines',
  'react pattern': 'tool calling',
  'short & long-term memory': 'memory systems',
  'human-in-the-loop': 'autonomous workflows',
  'agent safety': 'autonomous workflows',
  'max iteration limits': 'autonomous workflows',
  'observability for agents': 'monitoring',
  'background tasks': 'async ai systems',
  'caching llm responses': 'caching',
  'queues for inference': 'queues',
  'connection pooling': 'scaling ai apis',
  'timeout & circuit breakers': 'scaling ai apis',
  'batch embedding': 'embeddings',
  'api gateway patterns': 'scaling ai apis',
  'sse client patterns': 'streaming ui',
  'message components': 'ai chat ux',
  'syntax highlighting': 'markdown rendering',
  'stop & regenerate': 'ai chat ux',
  'conversation history': 'memory systems',
  'accessibility in chat ui': 'ai chat ux',
  'quantization basics': 'inference optimization',
  'langfuse & tracing': 'monitoring',
  'vllm & ollama': 'gpu deployment basics',
  'slas for ai features': 'ai cost optimization',
  'fallback strategies': 'production deployment',
  'security for ai apps': 'api security',
  'capstone integration': 'ai system architecture',
  'demo & storytelling': 'presentation skills',
  'ai portfolio presentation': 'presentation skills',
};

export function resolveTopicAlias(topic: string): string {
  const key = topic.toLowerCase().trim();
  return TOPIC_ALIASES[key] ?? key;
}
